[tool.isort]
include_trailing_comma = true
multi_line_output = 3
profile = "black"
skip_glob = ["popv/__init__.py"]

[tool.poetry]
name = "popv"
authors = ["Galen Xing", "Alexaner Tarashansky <alexander.tarashansky@czbiohub.org>", "Can Ergen <canergen.ac@gmail.com>"]
license = "BSD-3-Clause"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9"
]
description = "Automatic annotation of single cell data using a labelled reference dataset including various methods and giving certainty across those methods."
packages = [
  {include = "popv"},
]
version = "0.1.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
bbknn = "1.5.1"
black = {version = ">=22.3", optional = true}
codecov = {version = ">=2.0.8", optional = true}
flake8 = {version = ">=3.7.7", optional = true}
gdown = "3.13.0"
grpcio = "1.32.0"
h5py = ">=2.9.0"
huggingface-hub = "0.0.12"
imgkit = "1.2.2"
importlib-metadata = {version = "^1.0", python = "<3.8"}
ipython = {version = ">=7.20", optional = true, python = ">=3.7"}
ipywidgets = "*"
isort = {version = ">=5.7", optional = true}
jupyter = {version = ">=1.0", optional = true}
Markdown = "3.3.4"
nbconvert = {version = ">=5.4.0", optional = true}
nbformat = {version = ">=4.4.0", optional = true}
nbsphinx = {version = "*", optional = true}
nbsphinx-link = {version = "*", optional = true}
numpy = "1.19.2"
obonet = "0.3.0"
OnClass = "1.2"
pandas = ">=1.0"
pre-commit = {version = ">=2.7.1", optional = true}
pytest = {version = ">=4.4", optional = true}
rich = ">=9.1.0"
scanorama = "1.7.1"
scanpy = ">1.8.0"
scikit-learn = ">0.21.2,<1.0"
scikit-misc = "0.1.4"
scvi-tools = ">=0.15.0"
tensorflow = "2.2.0"
tensorboard = "2.2.2"
tqdm = "4.64.0"
six = "1.15.0"
typing-extensions = "4.2.0"

[tool.poetry.extras]
dev = ["black", "pytest", "flake8", "codecov", "scanpy", "loompy", "jupyter", "nbformat", "nbconvert", "pre-commit", "isort"]

[tool.poetry.dev-dependencies]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37

[testenv]
deps = pytest
extras =
    dev
commands = pytest {posargs}
"""
[build-system]
build-backend = "poetry.masonry.api"
requires = [
  "poetry>=1.0",
  "setuptools", # keep it here or "pip install -e" would fail
]
